  name: Cron Job
  on:
    schedule:
      - cron: '*/5 * * * *'
  jobs:
    # This workflow contains a single job called "cron"
    test_schedule:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Hello World
          run: echo "Hello world !!!"
