name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2
      - name: Deploy1
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} > my_private_key.pem
      - name: Deploy
        run: |
          ssh -i my_private_key.pem ohioncom@hioncoding.com
