name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v5
        id: echo-ssh-private-key
        with:
          script: |
            const fs = require('fs');
            const privateKey = '${{ secrets.SSH_PRIVATE_KEY }}';

            fs.writeFileSync('./my_private_key.pem', privateKey);
      - name: Deploy
        run: |
          ssh -i my_private_key.pem ohioncom@hioncoding.com
