name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2

      - name: Deploy
        run: |
          ssh -i $SSH_PRIVATE_KEY ohioncom@103.106.105.141
