name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2
      - name: Deploy1
        run: |
          # Log the SSH key
          echo "${SSH_PRIVATE_KEY:0:20}"
      - name: Deploy
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ohioncom@hioncoding.com
